"""Step 5: put an exported model into the DevEco watch project.

    python tools/05_make_watch_assets.py --model out/pico [--watch watch] [--per-page 4]

Generates:
  watch/entry/src/main/js/MainAbility/common/gn_meta.js   (model config for the JS runtime)
  watch/entry/src/main/js/MainAbility/pages/iNNN/          (installer pages carrying the weights)
  watch/entry/src/main/config.json                        (page list updated)
"""
import argparse
import base64
import json
import os
import shutil

CORE_PAGES = ["pages/index/index", "pages/kb/index", "pages/gen/index", "pages/bench/index"]
PAGE_JS_LIMIT = 40 * 1024     # real devices refuse pages whose compiled JS is ~48 KB+

HML = """<div class="root">
  <text class="t">{{msg}}</text>
</div>
"""
CSS = """.root {
  width: 466px;
  height: 466px;
  justify-content: center;
  align-items: center;
  background-color: #000000;
}
.t {
  width: 320px;
  height: 40px;
  font-size: 26px;
  color: #ffffff;
  text-align: center;
  text-overflow: ellipsis;
}
"""


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True, help="output dir of 04_export.py")
    ap.add_argument("--watch", default=os.path.join(here, "..", "watch"))
    ap.add_argument("--per-page", type=int, default=4, help="weight blocks per installer page")
    a = ap.parse_args()

    meta = json.load(open(os.path.join(a.model, "meta.json")))
    B = meta["B"]
    model = open(os.path.join(a.model, "model.bin"), "rb").read()
    vocab = open(os.path.join(a.model, "vocab.bin"), "rb").read()
    assert len(model) == meta["nBlocks"] * B
    meta["vocabBytes"] = len(vocab)

    js_root = os.path.join(a.watch, "entry/src/main/js/MainAbility")
    pages_dir = os.path.join(js_root, "pages")
    for d in os.listdir(pages_dir):
        if len(d) == 4 and d[0] == "i" and d[1:].isdigit():
            shutil.rmtree(os.path.join(pages_dir, d))

    items = [[("voc", vocab)]]
    blocks = [("w%03d" % i, model[i * B:(i + 1) * B]) for i in range(meta["nBlocks"])]
    for i in range(0, len(blocks), a.per_page):
        items.append(blocks[i:i + a.per_page])
    n = len(items)
    names = ["pages/i%03d/index" % k for k in range(n)]
    biggest = 0
    for k, group in enumerate(items):
        d = os.path.join(pages_dir, "i%03d" % k)
        os.makedirs(d)
        data = ",\n  ".join("['%s', '%s']" % (nm, base64.b64encode(b).decode()) for nm, b in group)
        nxt = ("'" + names[k + 1] + "'") if k + 1 < n else "''"
        js = ("// generated by tools/05_make_watch_assets.py - do not edit\n"
              "import inst from '../../common/gn_install.js';\n\n"
              f"var D = [\n  {data}\n];\n\n"
              "export default {\n"
              "  data: { msg: 'Installing...' },\n"
              f"  onReady() {{ inst.run(this, {k + 1}, {n}, D, {nxt}, '{meta['modelId']}'); }}\n"
              "}\n")
        biggest = max(biggest, len(js))
        assert len(js) < PAGE_JS_LIMIT, f"installer page {k} is {len(js)} bytes; lower --per-page"
        open(os.path.join(d, "index.js"), "w").write(js)
        open(os.path.join(d, "index.hml"), "w").write(HML)
        open(os.path.join(d, "index.css"), "w").write(CSS)

    with open(os.path.join(js_root, "common/gn_meta.js"), "w") as f:
        f.write("// generated by tools/05_make_watch_assets.py - do not edit\n")
        f.write("export default " + json.dumps(meta, indent=1) + ";\n")

    cfg_p = os.path.join(a.watch, "entry/src/main/config.json")
    cfg = json.load(open(cfg_p))
    cfg["module"]["js"][0]["pages"] = CORE_PAGES + names
    with open(cfg_p, "w") as f:
        json.dump(cfg, f, indent=2)
        f.write("\n")
    print(f"model {meta['name']} ({meta['modelId']}): {meta['nBlocks']} blocks of {B} B + vocab {len(vocab)} B")
    print(f"{n} installer pages, largest page JS {biggest / 1024:.1f} KB; config.json now lists {len(cfg['module']['js'][0]['pages'])} pages")


if __name__ == "__main__":
    main()
